services:
  web:
    image: nginx:stable-alpine
    container_name: astro-nginx
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
